### ISSUE TITLE
Unhandled rejection error Loopback 3.0

### ISSUE THREAD

**Issue by BostjanPisler** [studio-mv/loopback-softdelete-mixin#4]
Getting this error when deleting a model record that uses SoftDelete mixin.

`Unhandled rejection Error: Callback was already called.
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/async/dist/async.js:985:32
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/async/dist/async.js:3850:13
    at apply (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/async/dist/async.js:41:25)
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/async/dist/async.js:76:12
    at interceptInvocationErrors (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/strong-remoting/lib/remote-objects.js:683:22)
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/strong-remoting/lib/remote-objects.js:649:7
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/strong-remoting/lib/http-context.js:303:7
    at /Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/strong-remoting/lib/shared-method.js:269:11
    at tryCatcher (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/bostjanpisler/Dev/pepper/pepper-api/node_modules/bluebird/js/release/promise.js:691:18)`

**Comment by taimoor736** [comment]
Any update on this.? I am getting the same error.

**Comment by taimoor736** [comment]
@BostjanPisler did you find any fix for it?

**Comment by taimoor736** [comment]
I fount the fix this error. if you simply remove the return statements from these lines it will not cause the error. 

1. [line 25](https://github.com/gausie/loopback-softdelete-mixin/blob/master/src/soft-delete.js#L25)
2. [line 34](https://github.com/gausie/loopback-softdelete-mixin/blob/master/src/soft-delete.js#L34)
3. [line 45](https://github.com/gausie/loopback-softdelete-mixin/blob/master/src/soft-delete.js#L45)

thanks
